version: "3.7"

services:

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.init
    container_name: app
    hostname: app
    volumes:
      - ./app/opt:/opt
    ports:
      - "4000:4000"
    env_file:
      - ./app/.env
    networks:
      - public
      - private
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    build: ./db
    container_name: db
    hostname: db
    env_file:
      - ./db/.env
    volumes:
      - ./db/pgdata_store:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 15432:5432
    networks:
      - private
  
volumes:
 pgdata_store:
  driver: local
networks:
 public:
  driver: bridge
 private:
  driver: bridge